# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/go-rest-api internal/main.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run internal/main.go
  
  swagger.gen:
    desc: Generate Go code
    cmds:
    - GOFLAGS=-mod=mod go generate learningGo/go-rest-api/internal learingGo/go-rest-api/pkg/swagger

  swagger.validate:
    desc: Validate swagger
    cmds:
    - swagger validate swagger.yml
  
  swagger.doc:
    desc: Doc for swagger
    cmds:
    - docker run -i yousan/swagger-yaml-to-html < swagger.yml > doc/index.html

  swagger.doc:
    desc: Doc for swagger
    cmds:
    - docker run -i yousan/swagger-yaml-to-html < swagger.yml > doc/index.html

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
